[
    {
        inputUrl: 'https://www.instagram.com/masthedude',
        id: '3190287556033124257',
        type: 'Video',
        shortCode: 'CxGLaEctBeh',
        caption: "This song is about one's journey within themselves and exploring the realms of the unknown by escaping from what society believes to be true.\n" +
          '\n' +
          'All instruments, vocals and production by Masoud Moghaddari\n' +
          'All images in the video generated by AI image generation tool Midjourney. Animation, vfx and lyric video by DeadHead.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '#blackmetal #blackeneddeath #darkart #AI #aiartwork #aimusicvideo #blackmetalsong #newmusic #metal #metalguitar #metalmusic #growl #scream',
        hashtags: [
          'blackmetal',     'blackeneddeath',
          'darkart',        'AI',
          'aiartwork',      'aimusicvideo',
          'blackmetalsong', 'newmusic',
          'metal',          'metalguitar',
          'metalmusic',     'growl',
          'scream'
        ],
        mentions: [],
        url: 'https://www.instagram.com/p/CxGLaEctBeh/',
        commentsCount: 12,
        firstComment: '🔥🔥🔥🔥🔥',
        latestComments: [
          [Object], [Object],
          [Object], [Object],
          [Object], [Object],
          [Object], [Object],
          [Object], [Object]
        ],
        dimensionsHeight: 1137,
        dimensionsWidth: 640,
        displayUrl: 'https://scontent-lax3-1.cdninstagram.com/v/t51.2885-15/377575495_849010386956721_6185710869418588387_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-lax3-1.cdninstagram.com&_nc_cat=109&_nc_oc=Q6cZ2QFZIo8YTFBHjWcwX4q0htwNEaYgFxD_1-9RN-NnDcUiEQ2kFFfDsWF8yncxKCjsXtE&_nc_ohc=_pb9M8ft70cQ7kNvwHWL1DY&_nc_gid=kpNIZ8GJ-_o0UGb2VoULXw&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfHcn26MtEtGqyLyZy24r5wi86mxCxuLvNi7hrE2L1NAkw&oe=6808AD59&_nc_sid=10d13b',
        images: [],
        videoUrl: 'https://scontent-lax3-2.cdninstagram.com/o1/v/t16/f2/m82/AQP70h4l0FpaVvV99uYAWDtK5f7Bw5fYCSez9aRBlTcCm6c_spyFfRMLdLdKdy8zDrdRMx4caLhRW-bkWVZ_NnEE_KNWuTtOqrO1_h4.mp4?stp=dst-mp4&efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uY2xpcHMuYzIuNzIwLmJhc2VsaW5lIn0&_nc_cat=111&vs=1601156090690662_34783199&_nc_vs=HBksFQIYT2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfcHJvZC9ENjQxOTVDNzQ5ODJBRjc3NTkzNDM2QTcyQzAxMDY4RF92aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dGV19jeGJDU21JTHpzSUVBQ3BoNnNzOVFOQUJicV9FQUFBRhUCAsgBACgAGAAbABUAACbeq6efjLn3PxUCKAJDMywXQHaAhysCDEoYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HAA%3D%3D&_nc_rid=003ea7dbc4&ccb=9-4&oh=00_AfH7uUQbq9F-kGuLqCXMKSFZj063s0FSvpIHEl2F-Dmq_Q&oe=6804C3CE&_nc_sid=10d13b',
        alt: null,
        likesCount: 60,
        videoViewCount: 289,
        videoPlayCount: 794,
        timestamp: '2023-09-12T15:34:52.000Z',
        childPosts: [],
        ownerFullName: 'Dead God',
        ownerUsername: 'deadgodmetal',
        ownerId: '20261577438',
        productType: 'clips',
        videoDuration: 360.033,
        isSponsored: false,
        taggedUsers: [ [Object], [Object] ],
        musicInfo: {
          artist_name: 'deadgodmetal',
          song_name: 'Darker Than Everblack',
          uses_original_audio: true,
          should_mute_audio: false,
          should_mute_audio_reason: '',
          audio_id: '660912702690607'
        },
        coauthorProducers: [ [Object] ]
      },
      {
        inputUrl: 'https://www.instagram.com/masthedude',
        id: '3113254688774242195',
        type: 'Video',
        shortCode: 'Cs0gKULtT-T',
        caption: 'Checkout my new single "Chaos Recalls" with me doing the vocals for the first time!\n' +
          '@deadgodmetal \n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '#blackmetal #riffs #shredding #guitar #metalmusician #heavymetal #rock #riffwars #metalhead #heavymusic\n' +
          '#djent #djentleman #riffoftheday #guitarstagram #knowyourtone #musiciansdaily #gearporn #gearnerds #geartalk #guitarvideo  #guitardaily\n' +
          '#guitaristsofinstagram #guitarriff #instaguitar #guitarsarebetter #guitarfreak #guitargasm\n' +
          '@blackmetalpromotion @blackmetaltv @blackmetalgram',
        hashtags: [
          'blackmetal',       'riffs',
          'shredding',        'guitar',
          'metalmusician',    'heavymetal',
          'rock',             'riffwars',
          'metalhead',        'heavymusic',
          'djent',            'djentleman',
          'riffoftheday',     'guitarstagram',
          'knowyourtone',     'musiciansdaily',
          'gearporn',         'gearnerds',
          'geartalk',         'guitarvideo',
          'guitardaily',      'guitaristsofinstagram',
          'guitarriff',       'instaguitar',
          'guitarsarebetter', 'guitarfreak',
          'guitargasm'
        ],
        mentions: [
          'deadgodmetal',
          'blackmetalpromotion',
          'blackmetaltv',
          'blackmetalgram'
        ],
        url: 'https://www.instagram.com/p/Cs0gKULtT-T/',
        commentsCount: 65,
        firstComment: '🔥🔥🔥',
        latestComments: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
        dimensionsHeight: 1137,
        dimensionsWidth: 640,
        displayUrl: 'https://scontent-lhr8-1.cdninstagram.com/v/t51.2885-15/349339443_253663547316083_3923878626025655454_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-lhr8-1.cdninstagram.com&_nc_cat=111&_nc_oc=Q6cZ2QFbPUnAnpAmX0SdWqVDOE494wqKJrBYlxJpdrJ_1EiWdmgDu4YDTY8cgH1XxQbP3CI&_nc_ohc=Bk_B2CQbcbQQ7kNvwHGMOwe&_nc_gid=G4sQQwscE9c-yk15IvN8vA&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfFURvr8sSdW_BXPvKzfZGaRCIpljHTUipg6HTziv-cmGw&oe=6808C2AC&_nc_sid=10d13b',
        images: [],
        videoUrl: 'https://scontent-lhr6-1.cdninstagram.com/o1/v/t16/f2/m82/AQMjFXzd-Wv6WBtCLe1Ls1DQ1GCiHg_itVlBllq9FbfteAByrP4POCQ87hFcuF6TtsSCmXk7UWllNRAFQJMwgrz6lERSvvTkTlZJVgE.mp4?stp=dst-mp4&efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uY2xpcHMuYzIuNzIwLmJhc2VsaW5lIn0&_nc_cat=109&vs=1293855494549294_3635704716&_nc_vs=HBksFQIYT2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfcHJvZC9GQjQzNTkyMjI5M0Q3MzM3QUM2OUZEN0UyQUE1NDZCOV92aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dFVGkxQlFBUDBnX01Rd0NBTmEyZm0wdkpMazNicV9FQUFBRhUCAsgBACgAGAAbABUAACbasqrdgJflPxUCKAJDMywXQHPmZmZmZmYYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HAA%3D%3D&_nc_rid=c96db1bc35&ccb=9-4&oh=00_AfGKgoesfEzc3R4SGhANsHogJY0EedZzBOirec34yz0ucA&oe=6804CD6B&_nc_sid=10d13b',
        alt: null,
        likesCount: 199,
        videoViewCount: 967,
        videoPlayCount: 2404,
        timestamp: '2023-05-29T08:33:39.000Z',
        childPosts: [],
        ownerFullName: 'Masoud Moghaddari',
        ownerUsername: 'masthedude',
        ownerId: '3413538725',
        productType: 'clips',
        videoDuration: 318.4,
        isSponsored: false,
        taggedUsers: [ [Object] ],
        musicInfo: {
          artist_name: 'masthedude',
          song_name: 'Original audio',
          uses_original_audio: true,
          should_mute_audio: false,
          should_mute_audio_reason: '',
          audio_id: '3630014353954494'
        },
        coauthorProducers: [ [Object] ]
      },
      {
        inputUrl: 'https://www.instagram.com/masthedude',
        id: '2864653439242746804',
        type: 'Video',
        shortCode: 'CfBSyAaqju0',
        caption: 'Guitar Cover in a minute, Inception of the end by Trivium\n' +
          '@triviumband @matthewkheafy @coreytrivium @triviumpaolo\n' +
          '#riffs #shredguitar #guitar #metalmusician #heavymetal #rock #riffwars #metalhead #heavymusic\n' +
          '#djent #riffoftheday #guitarstagram #musiciansdaily #guitarvideo  #guitardaily\n' +
          '#guitaristsofinstagram #guitarriff #instaguitar #guitarsarebetter #guitarfreak #guitargasm',
        hashtags: [
          'riffs',            'shredguitar',
          'guitar',           'metalmusician',
          'heavymetal',       'rock',
          'riffwars',         'metalhead',
          'heavymusic',       'djent',
          'riffoftheday',     'guitarstagram',
          'musiciansdaily',   'guitarvideo',
          'guitardaily',      'guitaristsofinstagram',
          'guitarriff',       'instaguitar',
          'guitarsarebetter', 'guitarfreak',
          'guitargasm'
        ],
        mentions: [ 'triviumband', 'matthewkheafy', 'coreytrivium', 'triviumpaolo' ],
        url: 'https://www.instagram.com/p/CfBSyAaqju0/',
        commentsCount: 29,
        firstComment: '🤦🔥',
        latestComments: [
          [Object], [Object],
          [Object], [Object],
          [Object], [Object],
          [Object], [Object]
        ],
        dimensionsHeight: 1137,
        dimensionsWidth: 640,
        displayUrl: 'https://scontent-iad3-2.cdninstagram.com/v/t51.2885-15/289050186_3114535628860596_7239087322916074451_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-iad3-2.cdninstagram.com&_nc_cat=100&_nc_oc=Q6cZ2QH16lH_XWTvLSOHJQynyAjVFIKV5eeb6nFDTO51bBKmEbKNfi2gRP8Oc9ob4GiiYVpSnCQJXxNibOLS1PUNtaGE&_nc_ohc=USdV7t3YLvIQ7kNvwFxrKXC&_nc_gid=DQu8rgI2Oeppy58euJH02w&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfGYQUzDEwjR2Z4HMbAEgPqgxQn6eE7RRRjTC0w2RQkiCg&oe=6808BEE0&_nc_sid=10d13b',
        images: [],
        videoUrl: 'https://scontent-iad3-1.cdninstagram.com/o1/v/t16/f2/m86/AQMgS6B3OMTzxi0Fc5VQ-z_7CBt1uPIm-hu3FLhwM_3ePJ7U49mrAFpPfWlyCdBeGfeQNCkX-LHPdgC762Pj_UB-qs5p6_yKlm2xE4I.mp4?stp=dst-mp4&efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uY2xpcHMuYzIuNzIwLmJhc2VsaW5lIn0&_nc_cat=110&vs=406027115777976_1117843021&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9EQTQ2RjMzODRCM0M0RjVCRjA3MTJFMzQyMzhGNDk4NF92aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dBUWpIeEdXblowbkxpMEVBRkNUMTBJaERlb2VicV9FQUFBRhUCAsgBACgAGAAbABUAACau2%2BeTluDRPxUCKAJDMywXQE2MzMzMzM0YEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HAA%3D%3D&_nc_rid=51137ae800&ccb=9-4&oh=00_AfHOfX2Itl1pqLdcGvLxqEIFHl8N3IP255XlaY5uNpiFoA&oe=6804CC9C&_nc_sid=10d13b',
        alt: null,
        likesCount: 261,
        videoViewCount: 1004,
        videoPlayCount: 2252,
        timestamp: '2022-06-20T08:23:54.000Z',
        childPosts: [],
        ownerFullName: 'Masoud Moghaddari',
        ownerUsername: 'masthedude',
        ownerId: '3413538725',
        productType: 'clips',
        videoDuration: 59.1,
        isSponsored: false,
        taggedUsers: [ [Object] ],
        musicInfo: {
          artist_name: 'masthedude',
          song_name: 'Trivium-Inception Of The End guitar cover',
          uses_original_audio: true,
          should_mute_audio: false,
          should_mute_audio_reason: '',
          audio_id: '802829080643421'
        }
      },
      {
        inputUrl: 'https://www.instagram.com/masthedude',
        id: '2859794013419601284',
        type: 'Video',
        shortCode: 'CewB4Dcqf2E',
        caption: 'Please like & share 🤘\n' +
          'Death-Jealousy cover\n' +
          'Tribute to Chuck Schuldiner\n' +
          'Guitars: Masoud\n' +
          'Bass: @shahrumtehrani\n' +
          'Vocals: @raven_ekwon\n' +
          '\n' +
          '@deathofficial \n' +
          '@chuckschuldinerlove \n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '@igm_magazin #death #death_metal #riffs #shredguitar #chuckschuldiner @chuck_schuldiner_is_god @chuckschuldiner_fansclub #heavymusic #deathmetal #riffoftheday #metalmusic #musiciansdaily #guitaristsofinstagram #guitarsarebetter #guitarriff #guitargasm #riffwars #cover #coversong',
        hashtags: [
          'death',                 'death_metal',
          'riffs',                 'shredguitar',
          'chuckschuldiner',       'heavymusic',
          'deathmetal',            'riffoftheday',
          'metalmusic',            'musiciansdaily',
          'guitaristsofinstagram', 'guitarsarebetter',
          'guitarriff',            'guitargasm',
          'riffwars',              'cover',
          'coversong'
        ],
        mentions: [
          'shahrumtehrani',
          'raven_ekwon',
          'deathofficial',
          'chuckschuldinerlove',
          'igm_magazin',
          'chuck_schuldiner_is_god',
          'chuckschuldiner_fansclub'
        ],
        url: 'https://www.instagram.com/p/CewB4Dcqf2E/',
        commentsCount: 95,
        firstComment: 'DM it on 👉@MUSIC_TOWN_RECORDS ❤️',
        latestComments: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
        dimensionsHeight: 995,
        dimensionsWidth: 640,
        displayUrl: 'https://instagram.fotp7-2.fna.fbcdn.net/v/t51.2885-15/287666699_3206459499626934_8370348771956184863_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=instagram.fotp7-2.fna.fbcdn.net&_nc_cat=106&_nc_oc=Q6cZ2QFZYoVr7rEwpSYs9PqAf71dypTLY-aoqcxciv4-dfOew3XTyKpo1gu7EjXcwoh1d8E&_nc_ohc=cAIxy21a_5cQ7kNvwF1zZ1o&_nc_gid=UIGk3MCXSMRzkezs9_TqyQ&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfE1dAzfMEf9UXfgxzOJrtyFcYv49y_IF4fCIdjsu0SeDw&oe=6808CCCE&_nc_sid=10d13b',
        images: [],
        videoUrl: 'https://instagram.fotp7-2.fna.fbcdn.net/o1/v/t16/f2/m69/AQNycq2CuqyXCgSApWvT4yVczrHPbsZsGxT1kV6WVPUvzfJ02hrl81y8RZ_XRQcVdzM6o1VuS1sYjnSNNbq3pVeU.mp4?stp=dst-mp4&efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uaWd0di5jMi4xMjgwLmJhc2VsaW5lIn0&_nc_cat=108&vs=763802891304610_2326874052&_nc_vs=HBksFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HSUNXbUFERC1tdHZST2dCQUxiRlIxWHRrLXdMYnZWQkFBQUYVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dObTZFaEdWdmgwaTUwSUlBS3lTbm8wdVhzMVJidlZCQUFBRhUCAsgBACgAGAAbAYgHdXNlX29pbAExFQAAJur5kYCg1OI%2FFQIoAkMzLBdAa5ZmZmZmZhgSZGFzaF9iYXNlbGluZV8xX3YxEQB17AcA&_nc_rid=ebe293b554&ccb=9-4&oh=00_AfHFwjcm1eEfn4AnByvS2zWox6y--b7Vcp667bWDY_S1DQ&oe=6804D500&_nc_sid=10d13b',
        alt: null,
        likesCount: 225,
        videoViewCount: 1354,
        videoPlayCount: null,
        timestamp: '2022-06-13T15:32:51.000Z',
        childPosts: [],
        ownerFullName: 'Masoud Moghaddari',
        ownerUsername: 'masthedude',
        ownerId: '3413538725',
        productType: 'igtv',
        videoDuration: 220.7,
        isSponsored: false,
        taggedUsers: [ [Object], [Object], [Object] ]
      },
      {
        inputUrl: 'https://www.instagram.com/masthedude',
        id: '2893642399859873163',
        type: 'Video',
        shortCode: 'CgoSG52qBWL',
        caption: 'Guitar cover in 60 seconds-Mors Principium Est-The oppressed will rise \n' +
          '@morsprincipiumestofficial\n' +
          '#riffs #shredding #guitar #metalmusician #heavymetal #rock #riffwars #metalhead #heavymusic\n' +
          '#djent #djentleman #riffoftheday #guitarstagram #knowyourtone #musiciansdaily #gearporn #gearnerds #geartalk #guitarvideo  #guitardaily\n' +
          '#guitaristsofinstagram #guitarriff #instaguitar #guitarsarebetter #guitarfreak #guitargasm',
        hashtags: [
          'riffs',                 'shredding',
          'guitar',                'metalmusician',
          'heavymetal',            'rock',
          'riffwars',              'metalhead',
          'heavymusic',            'djent',
          'djentleman',            'riffoftheday',
          'guitarstagram',         'knowyourtone',
          'musiciansdaily',        'gearporn',
          'gearnerds',             'geartalk',
          'guitarvideo',           'guitardaily',
          'guitaristsofinstagram', 'guitarriff',
          'instaguitar',           'guitarsarebetter',
          'guitarfreak',           'guitargasm'
        ],
        mentions: [ 'morsprincipiumestofficial' ],
        url: 'https://www.instagram.com/p/CgoSG52qBWL/',
        commentsCount: 57,
        firstComment: 'داش مسعود😍 پنجه طلا 🙌🙌🙌❤️❤️❤️❤️❤️😍',
        latestComments: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
        dimensionsHeight: 1137,
        dimensionsWidth: 640,
        displayUrl: 'https://instagram.fgru10-1.fna.fbcdn.net/v/t51.2885-15/296208211_1455652994857301_7792178542466863257_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=instagram.fgru10-1.fna.fbcdn.net&_nc_cat=105&_nc_oc=Q6cZ2QHNnuaR3K1AvPPAu0UWP1SgsLmE-PPfW8dARCY7Lv48BGEg4B4GxL0Ba0xSVYaQND0&_nc_ohc=nqHyh6Hv5pcQ7kNvwH92CDY&_nc_gid=kj_MkubgblHx5Aw0F2E8tQ&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfFvTEaHDRZMl_V6NGCNhhJyBULwRwywcPjHWStueZYdBA&oe=6808BED6&_nc_sid=10d13b',
        images: [],
        videoUrl: 'https://instagram.fgru10-1.fna.fbcdn.net/o1/v/t16/f2/m86/AQNKCUjVGJrIMWBGenI_dC9tpoq3_hGdyFFO22lfQVLocppXNqGyJj71eqv1fPBtDjpfkTC5w_sRbMHyODaOmhzGHr5uG2EaVdjen-4.mp4?stp=dst-mp4&efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uY2xpcHMuYzIuNzIwLmJhc2VsaW5lIn0&_nc_cat=107&vs=526764326848170_972149169&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8zMTREMjhEQjFCNTI0MTZGOEFBM0MwOTE5QTZFMjVCOF92aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dHRm9vaEZLWU1XbXJGMEJBTzdDY0VkWExONDlicV9FQUFBRhUCAsgBACgAGAAbABUAACbyjtK2orzgPxUCKAJDMywXQE13bItDlYEYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HAA%3D%3D&_nc_rid=67a6c3770a&ccb=9-4&oh=00_AfERHKfiYh2HYVjoOKvByaPrzGJqd6rogZz5VoOJNuJP7w&oe=6804AC2A&_nc_sid=10d13b',
        alt: null,
        likesCount: 349,
        videoViewCount: 1847,
        videoPlayCount: 3598,
        timestamp: '2022-07-30T08:20:19.000Z',
        childPosts: [],
        ownerFullName: 'Masoud Moghaddari',
        ownerUsername: 'masthedude',
        ownerId: '3413538725',
        productType: 'clips',
        videoDuration: 58.933,
        isSponsored: false,
        taggedUsers: [ [Object] ],
        musicInfo: {
          artist_name: 'masthedude',
          song_name: 'Original audio',
          uses_original_audio: true,
          should_mute_audio: false,
          should_mute_audio_reason: '',
          audio_id: '735490557755701'
        }
      },
      {
        inputUrl: 'https://www.instagram.com/masthedude',
        id: '3164291607481942851',
        type: 'Video',
        shortCode: 'Cvp0nOttgND',
        caption: 'Meshuggah-Obzen [Vocal and Guitar one take cover]\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '#meshuggah #meshuggahband #cover #djent #mathmetal #metal #deathmetal #djentleman #guitargasm #guitarriff #guitarsarebetter #guitarporn #scream #growl #fryscream \n' +
          '@meshuggah @fredrik_thordendal @slussn @guitarsarebetter',
        hashtags: [
          'meshuggah',        'meshuggahband',
          'cover',            'djent',
          'mathmetal',        'metal',
          'deathmetal',       'djentleman',
          'guitargasm',       'guitarriff',
          'guitarsarebetter', 'guitarporn',
          'scream',           'growl',
          'fryscream'
        ],
        mentions: [ 'meshuggah', 'fredrik_thordendal', 'slussn', 'guitarsarebetter' ],
        url: 'https://www.instagram.com/p/Cvp0nOttgND/',
        commentsCount: 16,
        firstComment: '⛓🤘🍺🤘⛓',
        latestComments: [
          [Object], [Object],
          [Object], [Object],
          [Object], [Object],
          [Object], [Object]
        ],
        dimensionsHeight: 1137,
        dimensionsWidth: 640,
        displayUrl: 'https://scontent-lga3-1.cdninstagram.com/v/t51.2885-15/366133057_184992324464942_9150162664936814030_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-lga3-1.cdninstagram.com&_nc_cat=102&_nc_oc=Q6cZ2QEdk-nMw5xSx-OP8HtJN9FGTjoGUcu1ziLei0UKMorNU1WbU93zXkjKnxxz_MMuhmc&_nc_ohc=q62Mfo0lscUQ7kNvwGm4CjP&_nc_gid=lzGaL5niueObkfxlkTGJCQ&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfGuwQblLT1zP0kAycR4e4xO_j3WmrljJ_eDxry8dsTIeA&oe=6808CADB&_nc_sid=10d13b',
        images: [],
        videoUrl: 'https://scontent-lga3-2.cdninstagram.com/o1/v/t16/f2/m82/AQMByaz9ReCnRk71jH0nF0efWKbf4V41qqbeJDfqWwWhv-gwNJ1bVOkDKXBwnJ24Lbcav5T1aTh7KP6UsUWABNPK7mHyh5L9RvLz3w8.mp4?stp=dst-mp4&efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uY2xpcHMuYzIuMTA4MC5iYXNlbGluZSJ9&_nc_cat=105&vs=677225157597163_2342463330&_nc_vs=HBksFQIYT2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfcHJvZC81RDQyNTI1RTE5MUMyRTNBNTdBRjE1NTMwQTQ2OENCRF92aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dCQkIxeFVaYlpnYzhmQUJBTWVwMU8tQ3lTRWZicV9FQUFBRhUCAsgBACgAGAAbABUAACaQzt6syqT5PxUCKAJDMywXQHCcQYk3S8cYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HAA%3D%3D&_nc_rid=07d59e3463&ccb=9-4&oh=00_AfHrOjdXqMQ02JW_FP3MTZnfzsOkZd2DWYL3gae-8dctxg&oe=6804CDCE&_nc_sid=10d13b',
        alt: null,
        likesCount: 122,
        videoViewCount: 477,
        videoPlayCount: 710,
        timestamp: '2023-08-07T18:38:23.000Z',
        childPosts: [],
        locationName: 'Stockholm, Sweden',
        locationId: '213094275',
        ownerFullName: 'Masoud Moghaddari',
        ownerUsername: 'masthedude',
        ownerId: '3413538725',
        productType: 'clips',
        videoDuration: 265.766,
        isSponsored: false,
        taggedUsers: [ [Object] ],
        musicInfo: {
          artist_name: 'masthedude',
          song_name: 'Original audio',
          uses_original_audio: true,
          should_mute_audio: false,
          should_mute_audio_reason: '',
          audio_id: '330045006028081'
        },
        coauthorProducers: [ [Object] ]
      },
      {
        inputUrl: 'https://www.instagram.com/masthedude',
        id: '3122236783265437159',
        type: 'Video',
        shortCode: 'CtUac_jMdXn',
        caption: 'One take vocal cover of "The insight and the catharsis" by the mighty Dimmu Borgir.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '#blackmetal #metal #kvlt #grim #trve #dimmuborgir #shagrath #metal #deathmetal #black_metal #darkness #silenoz #icsvortex\n' +
          '@shagrathofficial @dimmuborgir @dimmusilenoz',
        hashtags: [
          'blackmetal',  'metal',
          'kvlt',        'grim',
          'trve',        'dimmuborgir',
          'shagrath',    'deathmetal',
          'black_metal', 'darkness',
          'silenoz',     'icsvortex'
        ],
        mentions: [ 'shagrathofficial', 'dimmuborgir', 'dimmusilenoz' ],
        url: 'https://www.instagram.com/p/CtUac_jMdXn/',
        commentsCount: 67,
        firstComment: 'such a wow 🔥',
        latestComments: [
          [Object], [Object],
          [Object], [Object],
          [Object], [Object],
          [Object]
        ],
        dimensionsHeight: 1137,
        dimensionsWidth: 640,
        displayUrl: 'https://scontent-iad3-1.cdninstagram.com/v/t51.2885-15/352427757_792364948943689_5991014447906716076_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-iad3-1.cdninstagram.com&_nc_cat=101&_nc_oc=Q6cZ2QEv3LHRdA_HUXaK3NZT9Cd1ZX0nmzLUtFXAmfm82WeNgM-ybjZ3eqhWn0BSjwHLWSQ&_nc_ohc=f0OLSbsc5AoQ7kNvwHVm6xw&_nc_gid=Xh7dJLE3T4rkvtjDpdTVpw&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfHMyBlWDjItM0MgeishHHxqOKU27H3_5UaX9txJrosk7g&oe=68089FD8&_nc_sid=10d13b',
        images: [],
        videoUrl: 'https://scontent-iad3-2.cdninstagram.com/o1/v/t16/f2/m82/AQOL7PadA-rdjhERhI4YiVoUHqi4vuynVisuTnXX4I5gAN9k4ZBu2ONMoMep_06Ne1LOAS8LMv9y6HvW3h2KMmIfLhUJxrTiR3P4zag.mp4?stp=dst-mp4&efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uY2xpcHMuYzIuMTI4MC5iYXNlbGluZSJ9&_nc_cat=111&vs=214197924813029_1491141180&_nc_vs=HBksFQIYT2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfcHJvZC9GMzRFQkY1MDc4NTA2NEQ1MkE4QzM5MkJEMjFEMThCMF92aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dIQWNraFNSZ0FPR0pkd0VBTC1qd0ZnYUVPeFZicV9FQUFBRhUCAsgBACgAGAAbABUAACaQh%2FjD1f%2BmQBUCKAJDMywXQHt%2B7ZFocrAYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HAA%3D%3D&_nc_rid=de40af7bd7&ccb=9-4&oh=00_AfHW9ayvhOjG2uvKzC6EswlGbzZR6TckRct8J0d-HmjTvg&oe=6804B0DA&_nc_sid=10d13b',
        alt: null,
        likesCount: 223,
        videoViewCount: 961,
        videoPlayCount: 1716,
        timestamp: '2023-06-10T17:58:08.000Z',
        childPosts: [],
        ownerFullName: 'Masoud Moghaddari',
        ownerUsername: 'masthedude',
        ownerId: '3413538725',
        productType: 'clips',
        videoDuration: 439.933,
        isSponsored: false,
        taggedUsers: [ [Object] ],
        musicInfo: {
          artist_name: 'masthedude',
          song_name: 'Original audio',
          uses_original_audio: true,
          should_mute_audio: false,
          should_mute_audio_reason: '',
          audio_id: '6287495971297569'
        }
      },
      {
        inputUrl: 'https://www.instagram.com/masthedude',
        id: '3072894771839587388',
        type: 'Video',
        shortCode: 'CqlHYObp1Q8',
        caption: 'A fun collab with the mighty @masguitardude \n' +
          '.\n' +
          'There will be many more. Please do support us by sharing and leave a comment to tell us how you enjoyed the video.\n' +
          'Cheers.\n' +
          '\n' +
          '#riffs #shredding #guitar #metalmusician #riffwars #metalhead #djent #djentleman #riffoftheday #guitarstagram #musiciansdaily  #guitarvideo #guitardaily #guitaristsofinstagram #guitarriff #guitarfreak #guitargasm #music #rock #drumlife #metal#modernmetal #drum #drums #drummer #drummers #iraniandrummer #iranian_drummer #iraniandrummer #metaldrumming #metaldrummer',
        hashtags: [
          'riffs',          'shredding',
          'guitar',         'metalmusician',
          'riffwars',       'metalhead',
          'djent',          'djentleman',
          'riffoftheday',   'guitarstagram',
          'musiciansdaily', 'guitarvideo',
          'guitardaily',    'guitaristsofinstagram',
          'guitarriff',     'guitarfreak',
          'guitargasm',     'music',
          'rock',           'drumlife',
          'metal',          'modernmetal',
          'drum',           'drums',
          'drummer',        'drummers',
          'iraniandrummer', 'iranian_drummer',
          'metaldrumming',  'metaldrummer'
        ],
        mentions: [ 'masguitardude' ],
        url: 'https://www.instagram.com/p/CqlHYObp1Q8/',
        commentsCount: 165,
        firstComment: 'باه باه عمو مسعوده که بنازممممم 😎✨❤️🔥',
        latestComments: [
          [Object], [Object],
          [Object], [Object],
          [Object], [Object],
          [Object], [Object]
        ],
        dimensionsHeight: 1920,
        dimensionsWidth: 1080,
        displayUrl: 'https://scontent-lga3-2.cdninstagram.com/v/t51.2885-15/339508903_190532700393319_4468651436239415213_n.jpg?stp=dst-jpg_e15_fr_p1080x1080_tt6&_nc_ht=scontent-lga3-2.cdninstagram.com&_nc_cat=107&_nc_oc=Q6cZ2QFzVlACCgeVGHckXEA_n8XI4Rfj_FrdFq53jfHJo_KQzXqNkUz_khWZW-7xFFl67CE&_nc_ohc=O57f_tR_8MoQ7kNvwFDYLIb&_nc_gid=UeYxHUcHhLFBPs2p-CyXEg&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfH0TyASYyUimwIvLpw_k-EtwxA9VKvI-ZEgrUbdg7wfOw&oe=68089C34&_nc_sid=10d13b',
        images: [],
        videoUrl: 'https://scontent-lga3-1.cdninstagram.com/o1/v/t16/f2/m82/AQNQKRUYLhponbk-OinnuNSSrhg2-iXXCcAhoaNQN7DWCBj6-HeygLJD_G07i3UgDwQ_RrP_6W7fUU1cRUek2RKtTwxl3WA0oSTa2eU.mp4?stp=dst-mp4&efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uY2xpcHMuYzIuNzIwLmJhc2VsaW5lIn0&_nc_cat=103&vs=1267294780865576_2520863054&_nc_vs=HBksFQIYT2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfcHJvZC83QjRFRTk2RjRFOTUwQzhBNDZCMkEwNDNENzAwRjBBRV92aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dIVVhKQlRzd0JtQVVmTUJBQmxGaEktNUpPaEticV9FQUFBRhUCAsgBACgAGAAbABUAACbotPH3hMGAQBUCKAJDMywXQFBXbItDlYEYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HAA%3D%3D&_nc_rid=cedb4df71c&ccb=9-4&oh=00_AfGq7J-rsg27TqDLWj3k252NmLaB04Icm-UITZW4R0pX3Q&oe=6804A9FD&_nc_sid=10d13b',
        alt: null,
        likesCount: 611,
        videoViewCount: 4190,
        videoPlayCount: 7907,
        timestamp: '2023-04-03T16:05:55.000Z',
        childPosts: [],
        ownerFullName: '🥁🎼Arta Ijadi Maghsoodi🥁🎼',
        ownerUsername: 'artaimaghsodi',
        ownerId: '477503400',
        productType: 'clips',
        videoDuration: 65.366,
        isSponsored: false,
        taggedUsers: [ [Object] ],
        musicInfo: {
          artist_name: 'artaimaghsodi',
          song_name: 'Original audio',
          uses_original_audio: true,
          should_mute_audio: false,
          should_mute_audio_reason: '',
          audio_id: '904306904185072'
        },
        coauthorProducers: [ [Object] ]
      },
      {
        inputUrl: 'https://www.instagram.com/masthedude',
        id: '2856721349331153096',
        type: 'Video',
        shortCode: 'CelHO6BKHDI',
        caption: 'Guitar cover in 60 seconds.\n' +
          'Children of bodom-Trashed, Lost and Strungout\n' +
          '@cobhc @alexilaiho.official\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '#riffs #shredguitar #guitar #metalmusician #heavymetal #rock #riffwars #metalhead #heavymusic #djent #riffoftheday #guitarstagram #musiciansdaily #gearporn #gearnerd #guitarvideo  #guitardaily #guitarriff #instaguitar #guitarsarebetter #guitarfreak #guitargasm',
        hashtags: [
          'riffs',          'shredguitar',
          'guitar',         'metalmusician',
          'heavymetal',     'rock',
          'riffwars',       'metalhead',
          'heavymusic',     'djent',
          'riffoftheday',   'guitarstagram',
          'musiciansdaily', 'gearporn',
          'gearnerd',       'guitarvideo',
          'guitardaily',    'guitarriff',
          'instaguitar',    'guitarsarebetter',
          'guitarfreak',    'guitargasm'
        ],
        mentions: [ 'cobhc', 'alexilaiho.official' ],
        url: 'https://www.instagram.com/p/CelHO6BKHDI/',
        commentsCount: 16,
        firstComment: '🔥🔥🔥🔥',
        latestComments: [
          [Object], [Object],
          [Object], [Object],
          [Object], [Object],
          [Object], [Object],
          [Object]
        ],
        dimensionsHeight: 1137,
        dimensionsWidth: 640,
        displayUrl: 'https://scontent-dfw5-1.cdninstagram.com/v/t51.2885-15/287052350_177357288058731_2166510016877657085_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-dfw5-1.cdninstagram.com&_nc_cat=103&_nc_oc=Q6cZ2QEC3JPUr4b639JsdmdLI94ItvIxpjHnipTHrprnC7ctksE7Flub4vCQLVYlFMyVMoTbegmZAyJxepIOslfS48_Q&_nc_ohc=8xiGFXMEVckQ7kNvwGXrPgf&_nc_gid=qbylxsDRPk8Twgwm8tWkpA&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfFE1pPsMsTW66u6STj2oV_9SKlyaseD8T7YZ4XUJ_NTuA&oe=6808B931&_nc_sid=10d13b',
        images: [],
        videoUrl: 'https://scontent-dfw5-2.cdninstagram.com/o1/v/t16/f2/m86/AQPNFtcPQTDVYmmOlbAVZYWDsZDV8EDN0X83h2ri_X0m4KVvNma9pejVER71xg9oWiRdk_mEP-VmKUYUVLtg82pEvnhXtGM15_MjeLQ.mp4?stp=dst-mp4&efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uY2xpcHMuYzIuNzIwLmJhc2VsaW5lIn0&_nc_cat=104&vs=1793017828103325_3985580967&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9FOTQ0MjcyMEI3RkI5QTM0RjQyRDg5MTRGN0YxNDlBNF92aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dITk5HUkZpMUpxdmxNNERBRlk2Y3dfN3FsOUJicV9FQUFBRhUCAsgBACgAGAAbABUAACaUmfOd%2FYjEPxUCKAJDMywXQE2AAAAAAAAYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HAA%3D%3D&_nc_rid=5d394c9502&ccb=9-4&oh=00_AfF4QIWvYj3HzjsthE6L8_fU_LmlImmrsRfj-cfgd3kIxQ&oe=6804C1C6&_nc_sid=10d13b',
        alt: null,
        likesCount: 353,
        videoViewCount: 3470,
        videoPlayCount: 8737,
        timestamp: '2022-06-09T09:46:05.000Z',
        childPosts: [],
        ownerFullName: 'Masoud Moghaddari',
        ownerUsername: 'masthedude',
        ownerId: '3413538725',
        productType: 'clips',
        videoDuration: 59,
        isSponsored: false,
        taggedUsers: [ [Object] ],
        musicInfo: {
          artist_name: 'masthedude',
          song_name: 'Trashed, lost & strungout by children of bodom',
          uses_original_audio: true,
          should_mute_audio: false,
          should_mute_audio_reason: '',
          audio_id: '534060534934572'
        }
      },
      {
        inputUrl: 'https://www.instagram.com/masthedude',
        id: '2840685397156805075',
        type: 'Video',
        shortCode: 'CdsJFFwK7nT',
        caption: 'Guitar cover in 60 secomds\n' +
          'Dark Tranquility- Format C: For Cortex\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '@darktranquillityofficial @miklstne \n' +
          '#metalmeme #riffs #shredguitar #guitar #metalmusician #heavymetal #rock #riffwars #metalhead #heavymusic\n' +
          '#djent #djentleman #riffoftheday #guitarstagram #knowyourtone #musiciansdaily #gearporn #gearnerds #geartalk #guitarvideo  #guitardaily\n' +
          '#guitaristsofinstagram #guitarriff #instaguitar #guitarsarebetter #guitarfreak #guitargasm',
        hashtags: [
          'metalmeme',        'riffs',
          'shredguitar',      'guitar',
          'metalmusician',    'heavymetal',
          'rock',             'riffwars',
          'metalhead',        'heavymusic',
          'djent',            'djentleman',
          'riffoftheday',     'guitarstagram',
          'knowyourtone',     'musiciansdaily',
          'gearporn',         'gearnerds',
          'geartalk',         'guitarvideo',
          'guitardaily',      'guitaristsofinstagram',
          'guitarriff',       'instaguitar',
          'guitarsarebetter', 'guitarfreak',
          'guitargasm'
        ],
        mentions: [ 'darktranquillityofficial', 'miklstne' ],
        url: 'https://www.instagram.com/p/CdsJFFwK7nT/',
        commentsCount: 37,
        firstComment: 'چه می‌کنه دادا🔥❤️',
        latestComments: [
          [Object], [Object],
          [Object], [Object],
          [Object], [Object],
          [Object], [Object]
        ],
        dimensionsHeight: 1137,
        dimensionsWidth: 640,
        displayUrl: 'https://scontent-det1-1.cdninstagram.com/v/t51.2885-15/281863680_172911358437113_7724393415616751236_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-det1-1.cdninstagram.com&_nc_cat=105&_nc_oc=Q6cZ2QEgWrlh8NkdQxP9bDcdw62abX32RfrxkGCbkxZhBYa9a7Flq5_ZowMJQ4JXPm_198hAhsr5eCniejCdUTkaED-w&_nc_ohc=rbmKt0B0G5EQ7kNvwEE6xLM&_nc_gid=vFGL7I7bL-NMpYs8gPm7fg&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfFlXTdBLb3F_PinymdFBQG9yxiNNZsUtkZIKVeriYLJEw&oe=6808B5E3&_nc_sid=10d13b',
        images: [],
        videoUrl: 'https://scontent-det1-1.cdninstagram.com/o1/v/t16/f2/m86/AQPl3rKth5ihWEM574fgevjXID8Ei_QCFdO5CyFaMUiK29OjemxPi4CCZ_8QU_cahO7NwRb2oQZl_ecYdOJL3rqL5O7b7CaMoy3U5Xs.mp4?stp=dst-mp4&efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uY2xpcHMuYzIuNzIwLmJhc2VsaW5lIn0&_nc_cat=107&vs=1702775530571257_111034584&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9DRTQyM0E5NkUyMTFEMURFQTNBN0Q4NTAxNzBDRjhBNV92aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dIYXF6eENOWUFlOVNNd0xBTEVqUkZ1Q1FrMEJicV9FQUFBRhUCAsgBACgAGAAbABUAACb0yqautZnZPxUCKAJDMywXQEyZmZmZmZoYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HAA%3D%3D&_nc_rid=deee0989b0&ccb=9-4&oh=00_AfEShdYB4O17BJBFigs8YGSD-0AFHGdKBsk7x2v7XJ-4Ww&oe=6804B361&_nc_sid=10d13b',
        alt: null,
        likesCount: 162,
        videoViewCount: 699,
        videoPlayCount: 1402,
        timestamp: '2022-05-18T06:48:54.000Z',
        childPosts: [],
        ownerFullName: 'Masoud Moghaddari',
        ownerUsername: 'masthedude',
        ownerId: '3413538725',
        productType: 'clips',
        videoDuration: 57.2,
        isSponsored: false,
        taggedUsers: [ [Object] ],
        musicInfo: {
          artist_name: 'masthedude',
          song_name: 'Dark Tranquility-Format C: For Cortex',
          uses_original_audio: true,
          should_mute_audio: false,
          should_mute_audio_reason: '',
          audio_id: '408829224196128'
        }
      },
      {
        inputUrl: 'https://www.instagram.com/masthedude',
        id: '2857768529936766116',
        type: 'Video',
        shortCode: 'Ceo1VY9K9Sk',
        caption: 'Re-upload\n' +
          'Guitar cover in 60 seconds.\n' +
          'Machine Head-Slanderous\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '#riffs #shredguitar #guitar #metalmusician #heavymetal #rock #machinehead #riffwars #metalhead #heavymusic #djent #riffoftheday #guitarstagram #musiciansdaily #gearporn #gearnerd #guitarvideo  #guitardaily #guitarriff #instaguitar #guitarsarebetter #guitarfreak #guitargasm',
        hashtags: [
          'riffs',            'shredguitar',
          'guitar',           'metalmusician',
          'heavymetal',       'rock',
          'machinehead',      'riffwars',
          'metalhead',        'heavymusic',
          'djent',            'riffoftheday',
          'guitarstagram',    'musiciansdaily',
          'gearporn',         'gearnerd',
          'guitarvideo',      'guitardaily',
          'guitarriff',       'instaguitar',
          'guitarsarebetter', 'guitarfreak',
          'guitargasm'
        ],
        mentions: [],
        url: 'https://www.instagram.com/p/Ceo1VY9K9Sk/',
        commentsCount: 19,
        firstComment: 'Tight 🔥 😎',
        latestComments: [
          [Object], [Object],
          [Object], [Object],
          [Object], [Object],
          [Object], [Object],
          [Object]
        ],
        dimensionsHeight: 1137,
        dimensionsWidth: 640,
        displayUrl: 'https://instagram.fcgh10-2.fna.fbcdn.net/v/t51.2885-15/286950327_1696454037371259_687034107608518247_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=instagram.fcgh10-2.fna.fbcdn.net&_nc_cat=103&_nc_oc=Q6cZ2QEJ0JtFLtv7f2CGAqT8B08T1K2Xbn5wCZL39Xsmg97jL4dD7314dmGHK_q_HbqoboB5uURQS3k0D9zTewGqi-C-&_nc_ohc=6_fLNfF0k7YQ7kNvwEZPqlA&_nc_gid=IyUV_D_T6n81foaFlOV4bw&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfEg_SiN7fl7HNLCdOlchcDKhsp6nbx8hT9xRu1lgpQB2Q&oe=6808A95E&_nc_sid=10d13b',
        images: [],
        videoUrl: 'https://instagram.fcgh10-2.fna.fbcdn.net/o1/v/t16/f2/m86/AQPx8JmK7osdDHCy1ETeTnw_KR9geEQD_AZxMK75r6z77U3357TV9gzQVweBUHKMl0iu9QDlW2_mmzqxE--uw6y1iw0bu_qZG-0T55k.mp4?stp=dst-mp4&efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uY2xpcHMuYzEuNzIwLmJhc2VsaW5lIn0&_nc_cat=103&vs=568728632772923_3068799498&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8wQjQ2MkY1NkE4NjE3NTA4QzUxRkQ2NkEyN0IyRkZBRF92aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dEdFNFQkduVVZvamxJMEJBSHFobjQ5V244ZDlicV9FQUFBRhUCAsgBACgAGAAbABUAACbYlJqk8JLcPxUCKAJDMywXQE1zMzMzMzMYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HAA%3D%3D&_nc_rid=9a0b7b1e0c&ccb=9-4&oh=00_AfEEuKs1PfeuIDVyGadQ0hEUk7vz5AUwq1RF8FzWMRerEw&oe=6804D763&_nc_sid=10d13b',
        alt: null,
        likesCount: 231,
        videoViewCount: 1314,
        videoPlayCount: 2673,
        timestamp: '2022-06-10T20:25:14.000Z',
        childPosts: [],
        ownerFullName: 'Masoud Moghaddari',
        ownerUsername: 'masthedude',
        ownerId: '3413538725',
        productType: 'clips',
        videoDuration: 58.9,
        isSponsored: false,
        taggedUsers: [ [Object] ],
        musicInfo: {
          artist_name: 'masthedude',
          song_name: 'Slanderous by Machine Head',
          uses_original_audio: true,
          should_mute_audio: false,
          should_mute_audio_reason: '',
          audio_id: '1383782765437331'
        }
      },
      {
        inputUrl: 'https://www.instagram.com/masthedude',
        id: '3276536469240708854',
        type: 'Video',
        shortCode: 'C14mI8WtH72',
        caption: 'This song is about ones greed and selfishness to make profit by making invaluable sacrifices that can not be replaced, including nature and humanity.\n' +
          '\n' +
          'All instruments, vocals and production by Masoud Moghaddari\n' +
          'Animation, vfx and lyric video by @im_dead_head\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '#deathmetal #deathcore #darkart #AI #aiartwork #aimusicvideo #deathmetalsong #newmusic #metal #metalguitar #metalmusic #growl #scream',
        hashtags: [
          'deathmetal',     'deathcore',
          'darkart',        'AI',
          'aiartwork',      'aimusicvideo',
          'deathmetalsong', 'newmusic',
          'metal',          'metalguitar',
          'metalmusic',     'growl',
          'scream'
        ],
        mentions: [ 'im_dead_head' ],
        url: 'https://www.instagram.com/p/C14mI8WtH72/',
        commentsCount: 58,
        firstComment: '🔥🔥🔥',
        latestComments: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
        dimensionsHeight: 1137,
        dimensionsWidth: 640,
        displayUrl: 'https://instagram.fosu2-2.fna.fbcdn.net/v/t51.29350-15/418643788_1135218300976624_3599627450394400705_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=instagram.fosu2-2.fna.fbcdn.net&_nc_cat=104&_nc_oc=Q6cZ2QFNFrkTaoNO2sFDfd9R4P4pOvuAo8Q4FcpsDjrEDDUdyQkZrJIb40ZpmujoccukdnFJU3cLusS3nkkR7-uZhOEi&_nc_ohc=e5ckzFzKMEgQ7kNvwGwQWFj&_nc_gid=QKzLQ7K-idAQciXMLh4Vlg&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfHL4GmRX931mykpYut19Oofa4Se8d1Hld603wYbvn1qPw&oe=68089F59&_nc_sid=10d13b',
        images: [],
        videoUrl: 'https://instagram.fosu2-2.fna.fbcdn.net/o1/v/t16/f2/m82/AQNffvKxJO5YM89sB77TFo7AhKcOz9xQSLTloRqXaWpnhiQuXlBaoLTrQ8VciPxhVhIO0LSNWcv8kbOkp_6-MLInD_5E9TZtog_UMlM.mp4?stp=dst-mp4&efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uY2xpcHMuYzIuMTA4MC5iYXNlbGluZSJ9&_nc_cat=110&vs=3512803569032427_1728280684&_nc_vs=HBksFQIYT2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfcHJvZC9FMjQ1QTdDMTgxNzA5QjQ1M0JCOEZEOTQ4RTZDNzFCM192aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dGUk4xQmlOSjdUYUF3Z0dBTDd1cUl1WTBvUlNicV9FQUFBRhUCAsgBACgAGAAbABUAACb8j9uw3ZKCQBUCKAJDMywXQHXDul41P30YEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HAA%3D%3D&_nc_rid=80b2ebf1b6&ccb=9-4&oh=00_AfHgu6rdJ5In4gqpVjhB6gqxwj0B87c3vMsQlvZO3bbw2A&oe=6804DA12&_nc_sid=10d13b',
        alt: null,
        likesCount: 202,
        videoViewCount: 1633,
        videoPlayCount: 6681,
        timestamp: '2024-01-09T15:24:34.000Z',
        childPosts: [],
        ownerFullName: 'Dead God',
        ownerUsername: 'deadgodmetal',
        ownerId: '20261577438',
        productType: 'clips',
        videoDuration: 348.233,
        isSponsored: false,
        taggedUsers: [ [Object] ],
        musicInfo: {
          artist_name: 'deadgodmetal',
          song_name: 'Original audio',
          uses_original_audio: true,
          should_mute_audio: false,
          should_mute_audio_reason: '',
          audio_id: '3745974172394348'
        },
        coauthorProducers: [ [Object] ]
      },
      {
        inputUrl: 'https://www.instagram.com/masthedude',
        id: '3185057700706219630',
        type: 'Video',
        shortCode: 'CwzmRqHt3Zu',
        caption: 'My new song is on the way and it is called "Darker Than Everblack". Stay tuned!\n' +
          'Video by @im_dead_head\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '#blackmetal #darkart #forbiddenknowledge #death #awakening #ai #midjourney',
        hashtags: [
          'blackmetal',
          'darkart',
          'forbiddenknowledge',
          'death',
          'awakening',
          'ai',
          'midjourney'
        ],
        mentions: [ 'im_dead_head' ],
        url: 'https://www.instagram.com/p/CwzmRqHt3Zu/',
        commentsCount: 16,
        firstComment: '🔥❤️',
        latestComments: [
          [Object], [Object],
          [Object], [Object],
          [Object], [Object],
          [Object]
        ],
        dimensionsHeight: 1137,
        dimensionsWidth: 640,
        displayUrl: 'https://scontent-phx1-1.cdninstagram.com/v/t51.2885-15/374210904_953357945728561_499906130305964468_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-phx1-1.cdninstagram.com&_nc_cat=101&_nc_oc=Q6cZ2QHBqhY37FTOnkAZiiJPHfYXHjqLpnTA67M3gHXPC_yzGG__FJG-t0myFB9LJ5AmaV4&_nc_ohc=2rIM9iKNDrkQ7kNvwFtcVHK&_nc_gid=UN88x-4xoRl6UIwOdDL5Cg&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfGOGigmc0k2vBosE0twfJ6W8BrLb-YygZKLK4BuMngM0Q&oe=6808BD1C&_nc_sid=10d13b',
        images: [],
        videoUrl: 'https://scontent-phx1-1.cdninstagram.com/o1/v/t16/f2/m82/AQOLzKIfgLVme-lJ8H7Lk7aNlDKtKx6mTT7Y9KAxnSGmq-s34z9Qi-ha6CqHlpmkV03Lq1UzUr0zVPDyaJydBGoaZViNtwWmGq50mOQ.mp4?stp=dst-mp4&efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uY2xpcHMuYzIuNzIwLmJhc2VsaW5lIn0&_nc_cat=101&vs=793128919274796_1679666457&_nc_vs=HBksFQIYT2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfcHJvZC84NzRGRkFDNDUyOThBNUFGRUIyRkM3QTMyREM2QkRCM192aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dJbWxUUmJocGtQeUpQc0ZBRU03OEpta1FYUWpicV9FQUFBRhUCAsgBACgAGAAbABUAACbepaHfrIyQQBUCKAJDMywXQCbdsi0OVgQYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HAA%3D%3D&_nc_rid=318b5674b1&ccb=9-4&oh=00_AfGl_urEdP4yC2ppG69Oqn7yLN2IP5nB-zB6RfFFyWD6iA&oe=6804C6C6&_nc_sid=10d13b',
        alt: null,
        likesCount: 104,
        videoViewCount: 347,
        videoPlayCount: 772,
        timestamp: '2023-09-05T10:10:46.000Z',
        childPosts: [],
        ownerFullName: 'Dead God',
        ownerUsername: 'deadgodmetal',
        ownerId: '20261577438',
        productType: 'clips',
        videoDuration: 11.433,
        isSponsored: false,
        taggedUsers: [ [Object] ],
        musicInfo: {
          artist_name: 'deadgodmetal',
          song_name: 'Original audio',
          uses_original_audio: true,
          should_mute_audio: false,
          should_mute_audio_reason: '',
          audio_id: '1993214527706424'
        },
        coauthorProducers: [ [Object] ]
      },
      {
        inputUrl: 'https://www.instagram.com/masthedude',
        id: '3153349691873427832',
        type: 'Video',
        shortCode: 'CvC8tZstAF4',
        caption: 'Meshuggah - Our Rage Won’t Die (Cover)\n' +
          '\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '@meshuggah @slussn @fredrik_thordendal @neuraldsp\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '.\n' +
          '#meshuggah #meshuggahband #djent #djentlemen #riffwars #metalmusic #metalvocal #guitarworld #strandbergguitars #strandbergboden8 #progressivemetal #periphery #monumentsband #metal #riffoftheday #guitars #guitarsdaily #guitarsolo #rockband #guitarshred',
        hashtags: [
          'meshuggah',         'meshuggahband',
          'djent',             'djentlemen',
          'riffwars',          'metalmusic',
          'metalvocal',        'guitarworld',
          'strandbergguitars', 'strandbergboden8',
          'progressivemetal',  'periphery',
          'monumentsband',     'metal',
          'riffoftheday',      'guitars',
          'guitarsdaily',      'guitarsolo',
          'rockband',          'guitarshred'
        ],
        mentions: [ 'meshuggah', 'slussn', 'fredrik_thordendal', 'neuraldsp' ],
        url: 'https://www.instagram.com/p/CvC8tZstAF4/',
        commentsCount: 34,
        firstComment: '😍😍😍😍',
        latestComments: [ [Object], [Object], [Object], [Object], [Object] ],
        dimensionsHeight: 1920,
        dimensionsWidth: 1080,
        displayUrl: 'https://scontent-ord5-3.cdninstagram.com/v/t51.2885-15/362892519_819109832852814_6416026501375557951_n.jpg?stp=dst-jpg_e15_fr_p1080x1080_tt6&_nc_ht=scontent-ord5-3.cdninstagram.com&_nc_cat=106&_nc_oc=Q6cZ2QGopjTlum2la46J0sPiYmZcZe0bmaFhkAL_lKyBgjVwYXLCkv8v8NqH9qkb3YevbilFrsEo1nlS0UdQho220zj7&_nc_ohc=1YrBqRzchSQQ7kNvwEc9NUe&_nc_gid=vVxrZTt1HPcn45lhg7lT8g&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfHVAEFRjy-JVmceO1piCOqrA6PbtDagtEu9STwIRQoGVw&oe=6808B008&_nc_sid=10d13b',
        images: [],
        videoUrl: 'https://scontent-ord5-3.cdninstagram.com/o1/v/t16/f2/m82/AQPLVGCzaj7TlQJOClorUQjQEdTI0MzQuO2WT4q_Cib4YxoTweqMa7QiJA-3MBvsRqOiWh-mDGXoMHKWO0GjYk4gJI2bqaq8x9iUoR8.mp4?stp=dst-mp4&efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uY2xpcHMuYzIuMTA4MC5iYXNlbGluZSJ9&_nc_cat=110&vs=240718298856821_2981958212&_nc_vs=HBksFQIYT2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfcHJvZC8zNTRCQzlGMzA3MkVBRUE3RkVBOUI5NENERjg5QjA4MF92aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dBdG5uUlVOc3RDdVh4MFpBTkJMQTltNXFHWWJicV9FQUFBRhUCAsgBACgAGAAbABUAACbUx4y6wpP%2BPxUCKAJDMywXQHF8zMzMzM0YEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HAA%3D%3D&_nc_rid=fa426d601b&ccb=9-4&oh=00_AfGItf4auVmWiVdlhU6bV21MTEGho9FSQNNqM94MExB5mg&oe=6804BB08&_nc_sid=10d13b',
        alt: null,
        likesCount: 121,
        videoViewCount: 535,
        videoPlayCount: 935,
        timestamp: '2023-07-23T16:14:21.000Z',
        childPosts: [],
        locationName: 'Stockholm, Sweden',
        locationId: '213094275',
        ownerFullName: 'Ray',
        ownerUsername: 'rational.dissonance',
        ownerId: '1310883681',
        productType: 'clips',
        videoDuration: 279.8,
        isSponsored: false,
        taggedUsers: [ [Object], [Object], [Object], [Object], [Object] ],
        musicInfo: {
          artist_name: 'rational.dissonance',
          song_name: 'Our Rage Won’t Die',
          uses_original_audio: true,
          should_mute_audio: false,
          should_mute_audio_reason: '',
          audio_id: '2051431111870028'
        },
        coauthorProducers: [ [Object] ]
      }
    ]